goals/urls.py
from django.conf.urls import url

from . import views

app_name = "goals"
urlpatterns = [
    url(r'^$',views.home,name = 'home'),
    url(r'^register/(?P<msg>[a-z]+)/$',views.register, name = 'register'),
    url(r'^confirm/(?P<user_name>\w+)/(?P<txref>\w+)/$',views.confirm, name = 'confirm'),
    url(r'^sign_up/$',views.sign_up, name = 'sign_up'),
    url(r'^sign_in/$',views.sign_in, name = 'sign_in'),
    url(r'^log_out/$',views.log_out, name = 'log_out'),
    url(r'^(?P<user_name>\w+)/(?P<msg>[a-z]+)/$', views.index, name = "index"),
    url(r'^(?P<user_name>\w+)/(?P<list_id>[0-9]+)/$',views.list_detail, name = 'list_detail'),
    url(r'^remove/(?P<user_name>\w+)/(?P<list_id>\w+)/(?P<goal_id>[0-9]+)/$',views.remove, name = "remove"),
    url(r'^rename/(?P<user_name>\w+)/(?P<list_id>\w+)/(?P<goal_id>\w+)/$',views.rename, name = "rename"),
    url(r'^add/(?P<user_name>\w+)/(?P<list_id>[0-9]+)/$',views.add, name = "add"),
    url(r'^save/(?P<user_name>\w+)/(?P<list_id>\w+)/(?P<goal_id>[0-9]+)/$',views.save, name = "save"),
        ]

my_life_goals/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r"^goals/",include("goals.urls")),
    url(r'^admin/', admin.site.urls),
]

goals/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):  #Model for extra user information
    owner = models.ForeignKey(User,default = 1,on_delete = models.CASCADE)
    sub = models.CharField(max_length = 100,default = "Basic")   #sub plan
    n_list = models.IntegerField(default = 0)
    n_goals = models.IntegerField(default = 0)
    def __str__(self):
        return (self.sub)

class Goals_list(models.Model):  #Model to store users different list of goals
    owner = models.ForeignKey(User,default = 1,on_delete = models.CASCADE)
    title = models.CharField(max_length = 250)
    def __str__(self):
        return self.title
    
class Goals(models.Model):   #Model to store goals users
    category = models.ForeignKey(Goals_list,on_delete = models.CASCADE)
    text = models.CharField(max_length = 450)
    hit = models.IntegerField(default=0)
    def __str__(self):
        return self.text

goals/views.py
'''
Three subscription has been created for the To-do List:
            Number_of_list(max) | Number_of_goals(max)  | Rename_Flag    | Remove_flag
Basic Plan          1           |         7             |    False       |  False
Starter Plan        1           |         12            |    False       |  False
Premium Plan       inf          |         inf           |    True        |  True
'''
#Models
from goals.models import Goals,Goals_list,Profile
from django.contrib.auth.models import User
#from django.contrib.auth.models import User
#Others
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate,login,logout
#from django.contrib.auth.decorators import login_required
#template and URL
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect
import requests,json
# Error messages and Notifications for users
messages = { 
                  "empty": None,
                  "a": "Email Exist",
                  "b": "Username Exist",
                  "c": "Registration_Successful", 
                  "d": "Wrong Password",
                  "e": "Username does not Exist",
                  "f": "Sign in to Continue",
                  "g": "list successfully created",
                  "h": "You can't create new list on your present subscription Plan,Kindly upgrade to enjoy this benefit",
                  "i": "You can't add on your present subscription Plan,Kindly upgrade to enjoy this benefit",
                  "j": "list successfully removed",
                  "k": "You can't remove list on your present subscription Plan,Kindly upgrade to enjoy this benefit",
                  "l": "You can't rename list on your present subscription Plan,Kindly upgrade to enjoy this benefit",
                  "m": "Payment Successfully completed",
                  "n": "Payment not Successful, Click on your interested subscription to try again",
            }

def update(user_name,sub):  #Updating Users' information after payment
    present_user = get_object_or_404(User,username = user_name);
    profile = Profile.objects.get(owner = present_user); profile.sub = sub; profile.save()
    return HttpResponseRedirect(reverse("goals:index", args = (user_name,"m",)))
    
def confirm(request,user_name,txref):   #Validating Payment From Server-Side
    data = {
            "txref": txref,
            "SECKEY": "FLWSECK-55903e651ec0038cafed9a20673c8bfc-X", 
            "include_payment_entity": "1",
            }
    url = "https://ravesandboxapi.flutterwave.com/flwv3-pug/getpaidx/api/xrequery"
    r = requests.post(url, data = json.dumps(data),headers = {"Content-Type":"application/json"} )
    response = r.json()
    if response['status'] == 'success':
        if response['data']['chargecode'] == '00':
            #Updating Users' information after payment
            if (response['data']['amount'] == 5000):
                return update(user_name,"Premium")  
            elif (response['data']['amount'] == 1000):
                return update(user_name,"Starter")
    else:
        return HttpResponseRedirect(reverse("goals:index", args = (user_name,"n",)))
    
@csrf_protect
def home(request):  #Home view
    return HttpResponseRedirect(reverse("goals:register", args = ("empty",)))
 
@csrf_protect
def sign_up(request): #Sign Up
    user_name = request.POST.get("user name")
    mail = request.POST.get("email")
    pword =request.POST.get("password")
    if User.objects.filter(email = mail).exists(): #Checking if Email exist prior to sign up
        return HttpResponseRedirect(reverse("goals:register", args = ( "a",)))
    elif User.objects.filter(username = user_name).exists():   #Checking if username exist prior to sign up
        return HttpResponseRedirect(reverse("goals:register", args = ( "b",)))
    else:
        new_user = User(username = user_name, email = mail) ; 
        new_user.set_password(pword); new_user.save()
        new_profile = Profile(owner = new_user); new_profile.save()
        return HttpResponseRedirect(reverse("goals:register", args = ("c",)))

@csrf_protect
def sign_in(request):
    user_name = request.POST.get("user name")
    pword = request.POST.get("password")
    if User.objects.filter(username = user_name).exists(): #Checking if user is signed-up
        present_user = authenticate(username = user_name, password = pword)
        if present_user:      
            login(request,present_user)
            return HttpResponseRedirect(reverse("goals:index", args = (user_name,"empty",)))
        else:
            return HttpResponseRedirect(reverse("goals:register", args = ("d",)))
    else:
        return HttpResponseRedirect(reverse("goals:register", args = ("e",)))
        
def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse("goals:register",args = ("empty",)))

@csrf_protect   
def register(request,msg): #register view for sogn-up and sign in
    template = loader.get_template("goals/register.htm")
    context = {"message":messages[msg]}
    tmp = template.render(context,request)
    return HttpResponse(tmp)

import time
def index(request,user_name,msg): #Index view that displays list of all goals
    present_user = get_object_or_404(User,username = user_name); 
    mail = present_user.email; mail = str(mail)
    txref = "mlg" + str(time.time()); txref = txref.replace(".","7")
    if request.user.is_authenticated:
        profile = Profile.objects.get(owner = present_user); sub = profile.sub
        g_list = present_user.goals_list_set.all()
        template = loader.get_template("goals/index.htm")
        context = {"goals_categories":g_list,
                   "user":present_user, 
                   "message":messages[msg], 
                   "sub":sub,
                   "mail": mail,
                   "txref": txref,
                   }
        tmp = template.render(context,request)
        return HttpResponse(tmp)
    else:
        return HttpResponseRedirect(reverse("goals:register", args = ("f",)))

def list_detail(request,user_name,list_id): #list_detail displays goals under each list
    present_user = get_object_or_404(User,username = user_name)
    if request.user.is_authenticated:
        present_list = get_object_or_404(Goals_list,pk = list_id)
        present_goals = present_list.goals_set.all()
        template = loader.get_template("goals/list_details.htm")
        context = {"goals":present_goals,"category":present_list, "user":present_user}
        tmp = template.render(context,request)
        return HttpResponse(tmp)
    else:
        return HttpResponseRedirect(reverse("goals:register", args = ("f",)))

def add(request,user_name,list_id): #add view for creating new list and new goals
    present_user = get_object_or_404(User,username = user_name)
    if request.user.is_authenticated:
        list_id = int(list_id);
        profile = Profile.objects.get(owner = present_user); sub = profile.sub
        if not (list_id): # A list is about to be created
            if sub == "Premium" or (sub != "Premium" and profile.n_list < 1):
                new_list = Goals_list(owner = present_user,title = request.GET.get("new_list"))
                new_list.save(); profile.n_list += 1;profile.save()
                return HttpResponseRedirect(reverse("goals:index",args = (user_name,"g")))
            else:
                return HttpResponseRedirect(reverse("goals:index", args = (user_name,"h")))
        else: # A goal is to be created
            if (sub == "Basic" and profile.n_goals <= 7) or (profile.sub == "Starter" and profile.n_goals <= 12 ) or profile.sub == "Premium":
                goals_category = get_object_or_404(Goals_list,pk = list_id)
                tmp = goals_category.goals_set.create(text = request.GET.get("new_goal"),hit = 1)
                tmp.save(); profile.n_goals += 1; profile.save()
                return HttpResponseRedirect(reverse("goals:list_detail",args = (user_name,list_id,)))
            else:
                return HttpResponseRedirect(reverse("goals:index", args = (user_name,"i")))
    else:
        return HttpResponseRedirect(reverse("goals:register", args = ("f",)))
   
def remove(request,user_name,list_id,goal_id): #remove view for removing existing list and goals
    present_user = get_object_or_404(User,username = user_name)
    if request.user.is_authenticated:
        goal_id = int(goal_id); present_user = User.objects.get(username = user_name)
        profile = Profile.objects.get(owner = present_user); sub = profile.sub
        if not goal_id: # A list is about to be removed
            if sub == "Premium" or sub == "Basic":  #Basic been activated for removal is just for Debugging purposes
                killed = get_object_or_404(Goals_list,pk = list_id); killed.delete()
                profile.n_list -= 1; profile.save()
                return HttpResponseRedirect(reverse("goals:index", args = (user_name, "j")))
            else:
                return HttpResponseRedirect(reverse("goals:index", args = (user_name,"k")))
        else: # A goal is to be removed from a list, This has to be adjusted in a future project by including time: once in a month for basic, once in a week for starter
            killed = get_object_or_404(Goals,pk = goal_id) 
            killed.delete(); profile.n_goals -= 1; profile.save()
            return HttpResponseRedirect(reverse("goals:list_detail", args = (present_user.username,list_id,)))
    else:
        return HttpResponseRedirect(reverse("goals:register", args = ("f",)))

def rename(request,user_name,list_id,goal_id): #rename view for renaming existing goals and lists
    present_user = get_object_or_404(User,username = user_name)
    if request.user.is_authenticated:
        goal_id = int(goal_id); present_user = User.objects.get(username = user_name)
        template = loader.get_template("goals/rename.htm")

goals/templates/goals/index.htm
<a href={% url 'goals:index' user.username "empty" %}><h1>mLG</h1></a> <!-- Home page of Users --> 

<ul>
Welcome {{user.username}},make LIFE GOOD by making your LIFE GOALS come true
</ul>

<!--  Display message and Payment button for users to upgrade their subscription -->
{%if sub != "Premium" %}
<ul>You are currently on  {{sub}}, kindly upgrade to the plans below to enjoy more</ul>
<form>
    <script type="text/javascript" src="https://ravesandboxapi.flutterwave.com/flwv3-pug/getpaidx/api/flwpbf-inline.js"></script>
    <button type="button" onClick="payWithRave(5000 )">Premium: 5000 Naira</button>
    {%if sub == "Basic" %}
    <script type="text/javascript" src="https://ravesandboxapi.flutterwave.com/flwv3-pug/getpaidx/api/flwpbf-inline.js"></script>
    <button type="button" onClick="payWithRave(1000)">Starter: 1000 Naira</button>
    {% endif %}
</form>

<!-- Rave API script -->
<script>
    const API_publicKey = "FLWPUBK-0137c7c59c9a7e988e449650043def66-X";
    
    function payWithRave(price) {
        var x = getpaidSetup({
            PBFPubKey: API_publicKey,
            customer_email: "{{ mail }}" ,
            amount: price,
            customer_phone: "2349032222708",
            currency: "NGN",
            payment_method: "both",
            txref: "{{txref}}",
            onclose: function() {},
            callback: function(response) {
                var txref = response.tx.txRef;
                console.log("This is the response returned after a charge", response);
                if (
                    response.tx.chargeResponseCode == "00" ||
                    response.tx.chargeResponseCode == "0"
                ) {
                        window.location.replace("{% url 'goals:confirm' user.username txref %}");//Redirecting to server-side validation
                } else {
                        window.location.replace("{% url 'goals:index' user.username 'n' %}");//Redirecting to users'homepage with an error message
                }

                x.close();
            }
        });
    }
</script>
{% endif %}

<!-- Notification for mLG users -->
{% if message %}
<font size = "3"
color = "red">{{message}}
</font>
{% endif %}

<!-- Displays all personal lists of a user, including remove and rename button -->
{% if goals_categories %}
<ul>
{% for list in goals_categories %}
<a href={% url 'goals:list_detail' user.username list.id %}><li>{{ list.title }} </li></a>
<form>
  <button formaction={% url 'goals:remove' user.username list.id 0 %}>remove</button>
  <button formaction={% url 'goals:rename' user.username list.id 0 %}>rename</button>
</form>
{% endfor %}
</ul>
{% else %}
<p>No list created yet.</p>
{% endif %}

<!-- A text box for creating a new list -->
<form method = "GET" action = {% url 'goals:add' user.username 0  %}>
  New List:<br>
  <input type="text" name="new_list"><br>
  <input type="submit" value="Create list">
</form>

<!-- logging out button -->
<form action = {% url 'goals:log_out' %}>
 <input type="submit" value="Log out">
</form>

goals/templates/goals/list_details.htm
<a href={% url 'goals:index' user.username "empty" %}><h1>mLG</h1></a><!-- Home page of Users -->

<!-- Displays all goals under the personal list of a user, including remove and rename button -->
{{ category.title }}
{% if goals %}
<ul>
{% for g in goals%}
<li>{{ g.text }}</li>
<form>
  <button formaction={% url 'goals:remove' user.username category.id g.id %}>remove</button>
  <button formaction={% url 'goals:rename' user.username category.id g.id %}>rename</button>
</form>
{% endfor %}
</ul>
{% else %}
<p>No goals added yet.</p>
{% endif %}

<!-- A text box for creating a new goal -->
<form action = {% url 'goals:add' user.username category.id %} >
  New goal<br>
  <input type="text" name="new_goal"><br>
  <input type="submit" value="Create Goal">
</form>

goals/templates/goals/register.htm
<h1>Welcometo mLG</h1>
make LIFE GOOD by making your LIFE GOALS come true
<br><br>

<!-- Notification to mLG Users-->
{% if message %}
<font size = "3"
color = "red">{{message}}
</font>
{% endif %}

<!-- Sign up -->
<form action= {% url 'goals:sign_up' %}  method = POST>
{% csrf_token %}
  <fieldset>
    <legend>SIGN-UP:</legend>
    EMAIL:<br>
    <input type="email" name="email"><br>
    USER NAME:<br>
    <input type="text" name="user name"><br>
    PASSWORD:<br>
    <input type="password" name="password"><br><br>
    <input type="submit" value="Submit">
  </fieldset>
</form>

<!-- Sign in -->
<form action= {% url 'goals:sign_in' %}  method = POST>
{% csrf_token %}
  <fieldset>
    <legend>SIGN-IN:</legend>
    USERNAME:<br>
    <input type="text" name="user name"><br>
    PASSWORD:<br>
    <input type="password" name="password"><br><br>
    <input type="submit" value="Submit">
  </fieldset>
</form>

goals/templates/goals/rename.htm
<a href={% url 'goals:index' user.username "empty" %}><h1>mLG</h1></a> <!-- Home page of Users -->

<!-- A text box for renaming lists -->
{% if list_text %}
<form action = {% url 'goals:save' user.username list_text.id 0 %} -->
  Enter New Name<br>
  <input type="text" name="new_name" value = {{list_text.title}}><br>
  <input type="submit" value="Save">
</form>

<!-- A text box for renaming goals -->
{% else %}
<form action = {% url 'goals:save' user.username goals_text.category.id goals_text.id %} >
  Enter New Name<br>
  <input type="text" name="new_name" value = {{goals_text.text}}><br>
  <input type="submit" value="Save">
{% endif %}

goals/templates/goals/test_run.html
<select name="cars">
  <form>
  <button formaction={% url 'goals:remove' category.id g.id %}>remove</button>
 </form>
</select>